# NUMPY 100 EXERCISES

1.  Import the numpy package under the name np

In [1]:
import numpy as np

2. Print numpy version and configuration

In [3]:
print('Numpy version:', np.__version__)
print('Numpy Configuration:', np.show_config())

Numpy version: 2.1.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30156",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30156",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-__cqtv8c/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

c:\Users\Danhaya\miniconda3\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. create null vector of size 10

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find memory size of any array

In [5]:
null_vector.nbytes

80

In [6]:
print("Size of one element: ", null_vector.itemsize)
print("Total elements: ", null_vector.size)
print('Total Memory: ', null_vector.nbytes)

Size of one element:  8
Total elements:  10
Total Memory:  80


5. How to get documentation of the numpy add function from the command line?

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

6. create a null vector of size 10 but the fifth value which is 1 

In [11]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49

In [13]:
values = list(range(10, 50))
vectors = np.array(values)
vectors

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse the vector 

In [15]:
reversed_vector = vectors[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. create 3x3 matrix with values ranging from 0 to 8

In [16]:
matrix = np.arange(9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find the indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [17]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
non_zero_indices

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix

In [2]:
import numpy as np

indentity_matrix = np.eye(3)
print(indentity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [6]:
arr = np.random.rand(3,3,3)
arr

array([[[0.74163442, 0.1109483 , 0.94763692],
        [0.46585186, 0.85431347, 0.48277474],
        [0.16588875, 0.1775789 , 0.09320142]],

       [[0.64736986, 0.89301261, 0.98884153],
        [0.17404274, 0.77781026, 0.24493503],
        [0.25377604, 0.37196628, 0.31082043]],

       [[0.30602667, 0.09166278, 0.73755232],
        [0.42228594, 0.12186832, 0.92529909],
        [0.74308649, 0.25310259, 0.1131226 ]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [8]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
arr = np.random.rand(10, 10)
arr




array([[6.01870783e-01, 7.34365417e-01, 7.34981347e-01, 9.31027698e-02,
        8.95781476e-01, 2.09214491e-01, 8.12166100e-01, 2.34186250e-01,
        3.92361121e-01, 9.64085467e-01],
       [4.39203612e-01, 2.39922851e-01, 4.70085593e-01, 8.94809703e-01,
        4.84244275e-02, 5.53573091e-01, 6.69700058e-01, 3.41350911e-01,
        4.45846154e-01, 2.86183884e-01],
       [4.99634828e-01, 4.65312813e-01, 4.06691508e-01, 2.63910744e-01,
        4.91852129e-01, 9.56905817e-01, 1.96595409e-01, 3.76671536e-01,
        4.51707283e-04, 1.59212204e-02],
       [5.76604075e-01, 7.45342361e-01, 9.76276676e-01, 6.36739166e-01,
        6.93806490e-01, 8.61998561e-02, 3.44053220e-01, 3.04862490e-01,
        6.06994108e-01, 4.54583204e-01],
       [4.26966694e-01, 4.02424300e-01, 5.62790220e-01, 4.70056596e-01,
        7.24679908e-01, 4.93156899e-01, 8.94201160e-01, 9.72093732e-01,
        8.45410989e-02, 9.68122501e-01],
       [4.87091486e-01, 1.59522998e-01, 4.45960929e-01, 6.89708744e-01,
   

In [16]:
print("minimun val: ", arr.min())
print("maximun val: ", arr.max())

minimun val:  0.0004517072830716451
maximun val:  0.9923975325353306


14. Create a random vector of size 30 and find the mean value

In [17]:
arr = np.random.rand(30)
print("mean :", np.mean(arr))

mean : 0.5570619306610542


15. Create a 2d array with 1 on the border and 0 inside