# NUMPY 100 EXERCISES

1.  Import the numpy package under the name np

In [1]:
import numpy as np

2. Print numpy version and configuration

In [3]:
print('Numpy version:', np.__version__)
print('Numpy Configuration:', np.show_config())

Numpy version: 2.1.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30156",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30156",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-__cqtv8c/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

c:\Users\Danhaya\miniconda3\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. create null vector of size 10

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find memory size of any array

In [5]:
null_vector.nbytes

80

In [6]:
print("Size of one element: ", null_vector.itemsize)
print("Total elements: ", null_vector.size)
print('Total Memory: ', null_vector.nbytes)

Size of one element:  8
Total elements:  10
Total Memory:  80


5. How to get documentation of the numpy add function from the command line?

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

6. create a null vector of size 10 but the fifth value which is 1 

In [11]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49

In [13]:
values = list(range(10, 50))
vectors = np.array(values)
vectors

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse the vector 

In [15]:
reversed_vector = vectors[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. create 3x3 matrix with values ranging from 0 to 8

In [16]:
matrix = np.arange(9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find the indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [17]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
non_zero_indices

(array([0, 1, 4]),)