# FUNDAMENTALS OF NUMPY

In [2]:
import numpy as np

data = list(range(10))
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## NUMPY ndarray: Multidimensional Array

In [4]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(data + data)

print(data.shape)
print(data.dtype)

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
int64


## Creating ndarrays

In [8]:
data = list(range(2, 10, 2))
arr = np.array(data)
arr

array([2, 4, 6, 8])

In [9]:
data = [[2, 4, 6], [8, 10, 12]]
arr2 = np.array(data)
arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
# how create zero matrix array

arr3 = np.zeros((3, 6))
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr4 = np.ones((4, 5))
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Data Types for ndarrays

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1
print(arr1.dtype)

float64


## Arithmetic with NumPy Arrays

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
double_array = arr * 2
double_array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [22]:
arr > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

## BASIC INDEXING AND SLICING

In [23]:
data = list(range(1, 20, 2))
arr = np.array(data)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
arr[5]

np.int64(11)

In [25]:
arr[5:8]

array([11, 13, 15])

In [26]:
arr[:7]

array([ 1,  3,  5,  7,  9, 11, 13])

In [27]:
arr[2:]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
arr_slice = arr[5:8]
arr_slice

array([11, 13, 15])

In [31]:
arr_slice[1] = 12
arr

array([ 1,  3,  5,  7,  9, 11, 12, 15, 17, 19])

In [33]:
# Two Dimensional Array

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [34]:
arr2d[0][1]

np.int64(2)

In [35]:
arr2d[0, 1]

np.int64(2)

In [36]:
# 3D Array

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

## BOOLEAN INDEXING

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will', 'Joe', 'Joe'])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4], [5,7]])

In [48]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [49]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4],
       [  5,   7]])

In [50]:
data.shape

(8, 2)

In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False, False])

In [52]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [53]:
data[names =='Will']

array([[ -5,   6],
       [-12,  -4]])

In [55]:
data[names == 'Will', :1]

array([[ -5],
       [-12]])

In [56]:
mask = (names == 'Bob') | (names == "Will")
mask

array([ True, False,  True,  True, False,  True, False, False])

In [57]:
data[mask]

array([[  4,   7],
       [ -5,   6],
       [  0,   0],
       [-12,  -4]])

## Fancy Indexing

In [59]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i]=i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [60]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [61]:
arr[[-1, -3, -2]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [63]:
arr = np.arange(32).reshape(8, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [66]:
arr[[3, 6, 5, 2], [0, 1, 2, 3]]

array([12, 25, 22, 11])

## Transposing Arrays And Swapping Axes

In [68]:
arr = np.arange(15).reshape((3, 5))
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [70]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [71]:
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [72]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
arr.swapaxes(0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Universal Functions: Fast Element - Wise Array Functions

In [1]:
import numpy as np


data = list(range(10))
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
sq_arr = np.sqrt(arr)
print(sq_arr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [3]:
arr_ex = np.exp(arr)
arr_ex

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
rng = np.random.default_rng()

x = rng.standard_normal(8)
y = rng.standard_normal(8)

x

array([-1.49241509,  1.69555482, -0.29441016,  0.40789111, -1.25463818,
       -0.04210328, -0.79123763, -0.22920506])

In [6]:
y

array([-2.39107772, -0.41473294,  0.60257172, -1.17816514, -1.98904384,
        0.99939716, -0.00594565,  1.57763587])

In [8]:
np.maximum(x, y)

array([-1.49241509,  1.69555482,  0.60257172,  0.40789111, -1.25463818,
        0.99939716, -0.00594565,  1.57763587])

In [9]:
np.minimum(x, y)

array([-2.39107772, -0.41473294, -0.29441016, -1.17816514, -1.98904384,
       -0.04210328, -0.79123763, -0.22920506])

In [12]:
rng = np.random.default_rng()
arr = rng.standard_normal(7) * 5
arr

array([-5.20131718,  3.76229371,  3.90917012, -9.09263218, -3.1051638 ,
       -0.25425222, -0.36073508])

In [13]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.20131718,  0.76229371,  0.90917012, -0.09263218, -0.1051638 ,
       -0.25425222, -0.36073508])

In [14]:
whole_part

array([-5.,  3.,  3., -9., -3., -0., -0.])

In [16]:
out = np.zeros_like(arr)
out

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.add(arr, 1)

array([-4.20131718,  4.76229371,  4.90917012, -8.09263218, -2.1051638 ,
        0.74574778,  0.63926492])

In [18]:
arr

array([-5.20131718,  3.76229371,  3.90917012, -9.09263218, -3.1051638 ,
       -0.25425222, -0.36073508])

In [19]:
np.subtract(arr, 10)

array([-15.20131718,  -6.23770629,  -6.09082988, -19.09263218,
       -13.1051638 , -10.25425222, -10.36073508])

In [20]:
out

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.add(arr, 1, out = out)

array([-4.20131718,  4.76229371,  4.90917012, -8.09263218, -2.1051638 ,
        0.74574778,  0.63926492])

In [22]:
out

array([-4.20131718,  4.76229371,  4.90917012, -8.09263218, -2.1051638 ,
        0.74574778,  0.63926492])